LANDMARK_NAMES = ["ConniferCluster", "GiantPalm", "House", "WaterWell",
                  "Mushroom", "Gorilla", "Windmill", "WoodBarrel",
                  "LionStatue", "TreasureChest", "Rock", "Stump", "Pillar",
                  "Tombstone", "WoodenChair", "FireHydrant", "OilDrum",
                  "TrafficCone", "Bench", "StreetLamp", "PhoneBox", "Anvil",
                  "Ladder", "Apple", "Banana", "RedFlowers", "YellowFlowers",
                  "Cactus", "RecycleBin", "Boat", "Barrel", "Barrel2",
                  "Beacon", "BigHouse", "Boletus", "Box", "BushTree3",
                  "BushTree2", "BushTree", "Coach", "Column", "Container",
                  "Dumpster", "GoldCone", "House1", "House2", "Jet",
                  "LowPolyTree", "LpPine", "Palm1", "Palm2", "Palm3", "Pickup",
                  "Pumpkin", "Soldier", "SteelCube", "Stone1", "Stone2",
                  "Stone3", "Tank", "Tower2", "TvTower", "Well"]
LANDMARK_NAMES = sorted(LANDMARK_NAMES) + ["NWCorner", "NECorner",
                                           "SWCorner", "SECorner"]

LANDMARK_HUMAN_NAMES = {
    "ConniferCluster": "cluster of trees",
    "GiantPalm": "palm tree",
    "House": "house",
    "WaterWell": "well",
    "Mushroom": "mushroom",
    "Gorilla": "gorilla",
    "Windmill": "windmill",
    "WoodBarrel": "barrel",
    "LionStatue": "lion statue",
    "TreasureChest": "treasure chest",
    "Rock": "rock",
    "Stump": "tree stump",
    "Pillar": "pillar",
    "Tombstone": "tombstone",
    "WoodenChair": "chair",
    "FireHydrant": "fire hydrant",
    "OilDrum": "oil drum",
    "TrafficCone": "traffic cone",
    "Bench": "bench",
    "StreetLamp": "street lamp",
    "PhoneBox": "phone booth",
    "Anvil": "anvil",
    "Ladder": "ladder",
    "Apple": "apple",
    "Banana": "banana",
    "RedFlowers": "red flowers",
    "YellowFlowers": "yellow flowers",
    "Cactus": "cactus",
    "RecycleBin": "recycling bin",
    "Boat": "boat",
    "Barrel": "barrel",
    "Barrel2": "barrel",
    "Beacon": "lighthouse",
    "BigHouse": "house",
    "Boletus": "mushroom",
    "Box": "box",
    "BushTree3": "bush",
    "BushTree2": "bush",
    "BushTree": "bush",
    "Coach": "bus",
    "Column": "column",
    "Container": "container",
    "Dumpster": "dumpster",
    "GoldCone": "cone",
    "House1": "house",
    "House2": "house",
    "Jet": "plane",
    "LowPolyTree": "pine tree",
    "LpPine": "pine tree",
    "Palm1": "fern",
    "Palm2": "fern",
    "Palm3": "fern",
    "Pickup": "car",
    "Pumpkin": "pumpkin",
    "Soldier": "soldier",
    "SteelCube": "steel cube",
    "Stone1": "stone",
    "Stone2": "stone",
    "Stone3": "stone",
    "Tank": "tank",
    "Tower2": "tower",
    "TvTower": "antenna",
    "Well": "well",
}

LANDMARK_RADII = {
    "ConniferCluster": 75,
    "GiantPalm": 75,
    "House": 125,
    "WaterWell": 75,
    "Mushroom": 75,
    "Gorilla": 75,
    "Windmill": 75,
    "WoodBarrel": 75,
    "LionStatue": 125,
    "TreasureChest": 75,
    "Rock": 75,
    "Stump": 75,
    "Pillar": 75,
    "Tombstone": 75,
    "WoodenChair": 75,
    "FireHydrant": 75,
    "OilDrum": 75,
    "TrafficCone": 75,
    "Bench": 125,
    "StreetLamp": 75,
    "PhoneBox": 75,
    "Anvil": 75,
    "Ladder": 75,
    "Apple": 75,
    "Banana": 75,
    "RedFlowers": 75,
    "YellowFlowers": 75,
    "Cactus": 75,
    "RecycleBin": 75,
    "Boat": 125,
    "Barrel": 75,
    "Barrel2": 75,
    "Beacon": 125,
    "BigHouse": 125,
    "Boletus": 75,
    "Box": 75,
    "BushTree3": 75,
    "BushTree2": 75,
    "BushTree": 75,
    "Coach": 125,
    "Column": 75,
    "Container": 110,
    "Dumpster": 75,
    "GoldCone": 75,
    "House1": 100,
    "House2": 100,
    "Jet": 120,
    "LowPolyTree": 75,
    "LpPine": 75,
    "Palm1": 85,
    "Palm2": 95,
    "Palm3": 100,
    "Pickup": 90,
    "Pumpkin": 75,
    "Soldier": 75,
    "SteelCube": 75,
    "Stone1": 75,
    "Stone2": 75,
    "Stone3": 75,
    "Tank": 100,
    "Tower2": 100,
    "TvTower": 75,
    "Well": 95
}

def get_all_landmark_names():
    return LANDMARK_NAMES

def get_name_of_landmark(i):
    return LANDMARK_NAMES[i]

def map_landmark_name_human(landmark_name):
    return LANDMARK_HUMAN_NAMES[landmark_name]

def get_landmark_radius(landmark_name):
    return LANDMARK_RADII[landmark_name] * 0.05